config/routes.rb
Rails.application.routes.draw do
  root to: 'planes#index'
  get '/planes', to: 'planes#index'
  get '/planes/new', to: 'planes#new'
  get '/planes/:id', to: 'planes#show'
  get '/planes/:id/edit', to: 'planes#edit'
  post '/planes', to: 'planes#create'
  put '/planes/:id', to: 'planes#update'
  

end

app/models/plane.rb
class Plane < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
    def index
      @planes = Plane.all
      render :index
    end
  
    def new
      render :new
    end
  
    def create
      plane = params.require(:plane).permit(:name, :kind, :description)
        plane = Plane.create(plane)
        redirect_to "/planes/#{plane.id}"
    end
  
    def show
        plane_id = params[:id]
        @plane = Plane.find(plane_id)
        render :show
    end
    
    def edit
        plane_id = params[:id]
        @plane = Plane.find(plane_id)
        render :edit
    end
  
  def update
        plane_id = params[:id]
        plane = Plane.find(plane_id)

        # get updated data
    updated_attributes = params.require(:plane).permit(:name, :kind, :description)
        # update the plane
        plane.update_attributes(updated_attributes)

        #redirect to show
        redirect_to "/posts/#{plane_id}"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RouteApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/planes/edit.html.erb
<form action="/planes/<%= @plane.id %>" method="post">
  <input name="_method" type="hidden" value="put" />  
  <input type="text" name="plane[name]" value="<%= @plane.name %>">
    <input type="text" name="plane[kind]" value="<%= @plane.kind %>">
    <textarea name="plane[description]" value="<%= @plane.description %>"></textarea>
    <%= token_tag form_authenticity_token %>

    <button> Update Plane </button>
</form>

app/views/planes/index.html.erb
Hello, all you eager pilots!

<% @planes.each do |plane| %>
  <div>
    <h2><%= plane.name %></h2>
    <p> <%= plane.kind %> </p>
    <a href="/planes/<%= plane.id %>">Show</a>
  </div>
<% end %>

app/views/planes/new.html.erb
<form action="/planes" method="post">
  <input type="text" name="plane[name]">
  <input type="text" name="plane[kind]">
  <textarea name="plane[description]"></textarea>
  <%= token_tag form_authenticity_token %>
  <button> Save Plane </button>
</form>

app/views/planes/show.html.erb
<div>
    Name: <%= @plane.name %> <br>
    Type: <%= @plane.kind %> <br>
    Description: <%= @plane.description %> <br> <br>
  <%= link_to 'Back', planes_path %>
</div>